style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/quay/quay
options:
  tag_filter_pattern: '[0-9]{4}\.[0-9]{2}\.[0-9]{2}'
  commits:
    sort_by: Scope
  commit_groups:
    group_by: Scope
  header:
    pattern: '^(\w*)\:\s(.*)\s(\(PROJQUAY-[0-9]+\))?$'
    pattern_maps:
      - Scope
      - Subject
      - JiraIssueId
  notes:
    keywords:
      - NOTE
      - BREAKING CHANGE
